### ISSUE TITLE
No longer present in the store

### ISSUE THREAD

**Issue by cpicon92** [garyjohnson/wpnest#6]
Why has wpnest been removed from the store? Will it be returning?

**Comment by garyjohnson** [comment]
Hi cpicon92,

Unfortunately I was asked to remove it from the store and I agreed to comply. 

My understanding is that while Nest does not currently have plans to make a WP app, they are considering it, and they are well aware of how “vocal” the WP community is, so my suggestion is to join that bandwagon and let them know you want an app. Thanks for your interest.

**Comment by mattlorimor** [comment]
I was worried about this. I suspect it's what happened to the other WP Nest app before this one. They've announced their public API developer program (http://venturebeat.com/2013/09/26/nest-opens-up-a-public-api-a-developer-program-and-maybe-even-an-app-store/). Maybe they'll be less hostile once they are providing an official API?

It's a little annoying that they keep asking for people to take down the apps that they write for controlling the Nest. I will be less annoyed, however, if they keep asking because they are going to push an official app.

**Comment by garyjohnson** [comment]
I took a look at their API sign-up and I think it's probably intended to create integration apps. I doubt they would allow API access for directly recreating client apps.

**Comment by BigBri41** [comment]
Mind sharing the contact information of the person that asked you to take it down.  I'm assuming you weren't trying to make a profit on the app and had it published for free right?
